### ISSUE TITLE
번역 버튼 추가

### ISSUE THREAD

**Issue by Hoto-Cocoa** [hotomoe/hotomoe#11]
슈플님이 해달랬음

**Comment by SWREI** [comment]
![image](https://github.com/hotomoe/io/assets/92716173/4ba8af78-2535-4156-964c-7f9f25720b68)
Powered by CherryPick(TM)

**Comment by Hoto-Cocoa** [comment]
개인적으로는 체리픽 디자인은 노트 컨텐츠랑 혼동의 여지가 있다고 보이고 버튼으로 빼는게 여러모로 나을 것 같네요

**Comment by SWREI** [comment]
> 개인적으로는 체리픽 디자인은 노트 컨텐츠랑 혼동의 여지가 있다고 보이고 버튼으로 빼는게 여러모로 나을 것 같네요

대충 노트 액션에 클립 동작 추가 하는 걸 참고해서 만들기
