### ISSUE TITLE
민감한 정보 숨기기 기능

### ISSUE THREAD

**Issue by seojangho** [hotomoe/hotomoe#17]
### Summary

클라이언트 단위로 on/off 토글이 가능함

켜져 있으면 DM이나 팔로우 온리 등 비공개 노트의 내용물이 기본적으로 표시되지 않음

### Purpose

방송 켜놓고 SNS 하는 사람들을 위한 기능

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by SWREI** [comment]
?

**Comment by Hoto-Cocoa** [comment]
![image](https://github.com/hotomoe/hotomoe/assets/21969938/27e80c86-0793-4905-9fd3-f873b98b3f74)

**Comment by seojangho** [comment]
+ 모더레이션 로그도 가리면 좋겠음

**Comment by Astro-CQM** [comment]
> * 모더레이션 로그도 가리면 좋겠음

this will be on #15

**Comment by Astro-CQM** [comment]
팔로워 노트는 해당 사항 없음.
다이렉트 범위의 모든 노트 및 모더레이션 기록, 사용자가 보유한 역할 목록을 가릴 수 있도록 조치

**Comment by Astro-CQM** [comment]
구현 완료, 추후 PR 예정
