### ISSUE TITLE
열람 주의 걸린 이미지/글 열람시 두번 클릭해야 보이는 옵션 

### ISSUE THREAD

**Issue by SuFl3770** [hotomoe/hotomoe#19]
### Summary

 * 클라이언트 설정에서 옵션을 활성화/비활성화 하는 방식
 * 옵션 활성화한 상태로 열람 주의 이미지/글을 누를시 한 번더 눌러야 뜨거나 다이얼로그 창이 떠 한번 더 물어봐주는 기능

### Purpose

지하철등 공공장소에서 아이고 손이 미끄러졌네 시전해서 발생하는 대참사를 방어해줌

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by SWREI** [comment]
열어도 미디어 오른쪽 위에 눈 모양 버튼 누르면 가려지는데 굳이 싶긴 함

**Comment by Hoto-Cocoa** [comment]
> 다시 가릴수 있는 옵션보다는 아예 실수로 노출되는걸 어느정도 방지하는 옵션이 필요한거긴 합니다 ... 근데 무엇보다도 눈 모양 버튼이 모바일 기준으로 좀 작아서 급하게 다시 숨기다가 이미지가 확대돼서 표시되는 대참사가(...)

확대 참사 ㅇㅈ

**Comment by Astro-CQM** [comment]
구현 완료, 추후 PR 예정
