### ISSUE TITLE
기본 언어를 한국어 또는 영어로 변경

### ISSUE THREAD

**Issue by Hoto-Cocoa** [hotomoe/hotomoe#27]
일본어가 뜨고 있어요
![image](https://github.com/hotomoe/hotomoe/assets/21969938/9aa1d09c-54fa-4d6d-a755-464125f79eca)

**Comment by nulta** [comment]
Ref: https://github.com/hotomoe/hotomoe/commit/e695c60a1dbe692bd0d4b07cfcb0dbce96210234
`표시 언어가 설정되지 않은 경우 브라우저 언어와 상관없이 일본어로 설정`
