### ISSUE TITLE
모바일 환경에서 uwu 로고가 매우 크게 보임 

### ISSUE THREAD

**Issue by hcho3** [hotomoe/hotomoe#32]
### 💡 Summary

1. uwu 모드로 호토모에를 방문합니다 (https://hoto.moe?uwu=true)
2. 크롬에서 개발자 모드를 켜고 모바일 모드로 전환합니다.
3. 디바이스 너비를 600 이하로 지정해 사이드바가 보이지 않게 합니다.

 

### 🥰 Expected Behavior

로고가 정상적인 크기로 보여야 합니다.

### 🤬 Actual Behavior

로고가 아주 크게 보여서 메뉴를 가릴 정도입니다.

![Screenshot 2024-06-21 161338](https://github.com/hotomoe/hotomoe/assets/2532981/a3261c3a-100c-431b-9942-db32744cd003)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Astro-CQM** [comment]
navbar-for-mobile.vue
instanceIconAlt 스타일 속성이 없어 발생하는 문제로 보임
