### ISSUE TITLE
커스텀 이모지 뮤트

### ISSUE THREAD

**Issue by Astro-CQM** [hotomoe/hotomoe#34]
### Summary

특정 이름을 가진 커스텀 이모지를 뮤트함

### Purpose

사용자 요청

### Do you want to implement this feature yourself?

- [x] Yes, I will implement this by myself and send a pull request

**Comment by Astro-CQM** [comment]
특정 shortcode를 가진 이모지를 발견 시 이를 heart로 대체

**Comment by hcho3** [comment]
이 기능 구현은 진척이 어느정도 되었나요?

**Comment by Astro-CQM** [comment]
로컬에 일단 뮤트한 내용을 받아서 저장하는 것과 불러오는 것까지는 가능한 정도로 되어 있습니다!
뮤트 기능 자체를 어떻게 처리할 지 고민하고 있어요...

**Comment by hcho3** [comment]
> 뮤트 기능 자체를 어떻게 처리할 지 고민하고 있어요...

> 특정 shortcode를 가진 이모지를 발견 시 이를 heart로 대체

클라이언트 상에서 heart로 대체하는걸로는 충분치 않나요?

**Comment by Astro-CQM** [comment]
Upstream에서 개발된 기능으로 보여 닫습니다.
