### ISSUE TITLE
사유가 전혀 지정되지 않은 신고의 발송을 제한

### ISSUE THREAD

**Issue by Astro-CQM** [hotomoe/hotomoe#38]
### Summary

사유 또는 카테고리 중 하나라도 지정되지 않은 신고를 제한

### Purpose

신고 처리를 용이하게...?

### Do you want to implement this feature yourself?

- [x] Yes, I will implement this by myself and send a pull request

**Comment by Hoto-Cocoa** [comment]
근데 카테고리가 신고 확인할 때 안보이던데

**Comment by Astro-CQM** [comment]
제어판 신고 탭에 들어가면 신고자 아래에 카테고리가 표시됩니다 (로컬 한정)

**Comment by Hoto-Cocoa** [comment]
![image](https://github.com/user-attachments/assets/3b076738-9c2a-452a-9bf7-0e3aa3379c2e)
![image](https://github.com/user-attachments/assets/a1ab71c6-8284-453f-a8aa-0bfb8c495642)

어떻게 해도 뜨질 않더라고요... 내 문제인가?

**Comment by Astro-CQM** [comment]
> 어떻게 해도 뜨질 않더라고요... 내 문제인가?

버그인 거 같은데요?
나중에 확인해보겠읍니다
