### ISSUE TITLE
"민감한 내용의 미디어를 더블 클릭해서 표시" 옵션을 사용 시 이미지 확대가 안됨

### ISSUE THREAD

**Issue by SuFl3770** [hotomoe/hotomoe#40]
### 💡 Summary

말 그대로 민감한 내용의 미디어를 더블 클릭해서 표시 옵션을 사용하면 민감한 미디어 상관 없이 모든 이미지가 확대가 안됨

### 🥰 Expected Behavior

이미지를 확대해서 보여줌

### 🤬 Actual Behavior

반응이 없음

### 📝 Steps to Reproduce

1. 확대해서 볼 이미지를 누른다. (열람 주의 이미지일 경우 더블 클릭후 누른다.)
2. 반응이 없다.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 23H2, Android 14 (OneUi 6.1.1)
* Browser: Whale 3.27.254.15(Chrome/126.0.0.0), Chrome 127.0.6533.103
* Server URL: Hoto.moe
* Misskey: 2024.5.0-hotomoe.4
```

### 🛰 Backend Environment (for server admin)

```markdown
-
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Astro-CQM** [comment]
예상했던 버그였는데
진짜 발생해버리고 말았음

**Comment by Astro-CQM** [comment]
숨겨져 있는 경우와 숨겨지지 않은 경우에 관계 없이 기존 이벤트를 전부 prevent 해버려서 발생한 문제로 확인됨
