### ISSUE TITLE
MemoryKVCache 수동 clear

### ISSUE THREAD

**Issue by Hoto-Cocoa** [hotomoe/hotomoe#8]
[MemoryKVCache](https://github.com/hotomoe/misskey/blob/bb3117f70a35f7d9586b010ff6abe65a08d60b7a/packages/backend/src/misc/cache.ts#L189)를 수동으로 clear 하거나 할 수 있었으면 좋겠음

**Comment by SWREI** [comment]
Ref:
https://github.com/hotomoe/io/blob/76529f220a973734221b9edda7bc433f77c8270b/packages/backend/src/core/CacheService.ts#L183

**Comment by Astro-CQM** [comment]
구현 완료, 추후 PR 예정
